namespace KWP
{
    public enum KWPNegativeResponseCode
    {
        GENERAL_REJECT = 0x10,
        SERVICE_NOT_SUPPORTED = 0x11,
        SUBFUNCTION_NOT_SUPPORTED_OR_INVALID_FORMAT = 0x12,
        BUSY_REPEAT_REQUEST = 0x21,
        CONDITIONS_NOT_CORRECT_OR_REQUEST_SEQUENCE_ERROR = 0x22,
        ROUTINE_NOT_COMPLETE_OR_SERVICE_IN_PROGRESS = 0x23,
        REQUEST_OUT_OF_RANGE = 0x31,
        SECURITY_ACCESS_DENIED_OR_REQUESTED = 0x33,
        INVALID_KEY = 0x35,
        EXCEED_NUMBER_OF_ATTEMPTS = 0x36,
        REQUIRED_TIME_DELAY_NOT_EXPIRED = 0x37,
        DOWNLOAD_NOT_ACCEPTED = 0x40,
        IMPROPER_DOWNLOAD_TYPE = 0x41,
        CANNOT_DOWNLOAD_TO_SPECIFIED_ADDRESS = 0x42,
        CANNOT_DOWNLOAD_NUMBER_OF_BYTES_REQUESTED = 0x43,
        UPLOAD_NOT_ACCEPTED = 0x50,
        IMPROPER_UPLOAD_TYPE = 0x51,
        CANNOT_UPLOAD_FROM_SPECIFIED_ADDRESS = 0x52,
        CANNOT_UPLOAD_NUMBER_OF_BYTES_REQUESTED = 0x53,
        TRANSFER_SUSPENDED = 0x71,
        TRANSFER_ABORTED = 0x72,
        ILLEGAL_ADDRESS_IN_BLOCK_TRANSFER = 0x74,
        ILLEGAL_BYTE_COUNT_IN_BLOCK_TRANSFER = 0x75,
        ILLEGAL_BLOCK_TRANSFER_TYPE = 0x76,
        BLOCK_TRANSFER_DATA_CHECKSUM_ERROR = 0x77,
        REQUEST_CORRECTLY_RECEIVED_RESPONSE_PENDING = 0x78,
        INCORRECT_BYTE_COUNT_DURING_BLOCK_TRANSFER = 0x79,
        SERVICE_NOT_SUPPORTED_IN_ACTIVE_DIAGNOSTIC_SESSION = 0x80
    }
}
